type:build:
  - ".github/**/*"
  - ".coveralls.yml"
  - ".gitignore"
  - "phpcs.xml"

dependencies:
  - "composer.json"
  - "composer.lock"

type:helper:
  - "src/helpers.php"

type:tests:
  - 'tests/**/*'
  - 'phpunit.xml.dist'

theme:docs:
  - "README.md"
  - "LICENSE"
  - "CONTRIBUTING.md"
  - "CODE_OF_CONDUCT.md"